#PBS -N Cri
#PBS -j eo
#PBS -e /var/www/html/virhost/results/$random/virhost.err
#PBS -q batch
#PBS -l nodes=1:ppn=4
# This jobs working directory is set below

echo Running on host `hostname`
echo Time is `date`

cd /scratch/working/$random
echo Working directory is `pwd`
touch /scratch/working/$random/made_it

# run the job
/var/www/html/virhost/scripts/virhost.sh $ncbiid
cp /scratch/working/$random/* /var/www/html/virhost/results/$random/.
